/**
 * Regenerates `db/setup.sql` — the single file that sets up a fresh database
 * from a web SQL console (Neon, Supabase, pgAdmin), with no local tooling.
 *
 * It builds a throwaway local database from the real migrations and the real
 * seed script, then dumps it. Deriving the file rather than hand-writing it is
 * what keeps it honest: it cannot drift from the migrations.
 *
 * Run after any schema or seed change. Requires a local Postgres and pg_dump.
 */
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

const HOST = process.env.EXPORT_PG_HOST ?? '/tmp'
const PORT = process.env.EXPORT_PG_PORT ?? '55432'
const USER = process.env.EXPORT_PG_USER ?? 'postgres'
const DB = 'vocamap_sql_export'
const OUT = 'db/setup.sql'

const url = `postgresql://${USER}@localhost:${PORT}/${DB}`

function psql(database: string, sql: string): void {
  execFileSync('psql', ['-h', HOST, '-p', PORT, '-U', USER, '-d', database, '-c', sql], {
    stdio: 'pipe',
  })
}

function run(command: string, args: string[], env: Record<string, string> = {}): string {
  return execFileSync(command, args, {
    env: { ...process.env, ...env },
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
}

psql('postgres', `drop database if exists ${DB}`)
psql('postgres', `create database ${DB}`)

run('npx', ['tsx', 'scripts/migrate.ts'], { DATABASE_URL_UNPOOLED: url })
run('npx', ['tsx', 'scripts/seed.ts'], { DATABASE_URL: url })

const dump = run('pg_dump', [
  '-h', HOST, '-p', PORT, '-U', USER, '-d', DB,
  '--no-owner',
  '--no-privileges',
  '--no-tablespaces',
  '--no-comments',
  '--inserts',
  '--quote-all-identifiers',
])

const body = dump
  // psql meta-commands (\restrict, \unrestrict) are not SQL and make a web
  // console reject the whole script.
  .split('\n')
  .filter((line) => !line.startsWith('\\'))
  .join('\n')
  .replace(/\n{3,}/g, '\n\n')
  .trim()

const header = `--
-- Voca Brain Map — database setup
--
-- Generated by \`pnpm db:export-sql\`. Do not edit by hand; edit the Drizzle
-- schema or the seed script and regenerate.
--
-- Creates every table, type, index and constraint, and inserts the seed
-- vocabulary with its approved Brain Maps. Contains no user accounts and no
-- passwords — sign up in the app to create yours.
--
-- Run once, on an empty database.
--
`

writeFileSync(OUT, `${header}\n${body}\n`)
psql('postgres', `drop database if exists ${DB}`)

const lines = body.split('\n').length
console.log(`✓ wrote ${OUT} (${lines} lines, ${(body.length / 1024).toFixed(0)} KB)`)
